# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170413_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='furious',
            name='neg',
            field=models.FloatField(default=0.5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furious',
            name='neu',
            field=models.FloatField(default=0.5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furious',
            name='pos',
            field=models.FloatField(default=0.5, max_length=100),
            preserve_default=False,
        ),
    ]
