# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20170413_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furious',
            name='neg',
        ),
        migrations.RemoveField(
            model_name='furious',
            name='neu',
        ),
        migrations.RemoveField(
            model_name='furious',
            name='pos',
        ),
    ]
