# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20170413_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='furious',
            new_name='table',
        ),
    ]
