# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20170413_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='age_gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField()),
                ('gender', models.TextField()),
            ],
        ),
    ]
